### PR TITLE
Switch to figwheel

### PR DESCRIPTION
**Pull request by heyarne**
As suggested in #10, this adds Figwheel, which enables hot-swapping of changed code. What would be nice is if there was some additional build that bundles and minifies everything for production.

### CODE REVIEW

**Comment by heyarne** [comment]
I just added an optimized build via `lein cljsbuild once optimized`.

**Comment by nbeloglazov** [comment]
Thanks Arne! I tested the patch locally and works great. One question about code. You added `first-run?` variable to make sure that sketch is not initialized multiple times. Why would it be initialized multiple times with figwheel? run-sketch function is called only once from html page. Figwheel affects it somehow?

**Comment by heyarne** [comment]
Yes, figwheel affects this. In the project.clj [figwheel is configured](https://github.com/heyarne/quil-templates/blob/feature/switch-to-figwheel/cljs/src/leiningen/new/quil_cljs/project.clj#L18) to call this function when reloading the code. This enables things like resetting state.

One could also set `:figwheel true`, remove the `first-run?` and call `run-sketch` manually (in the HTML or in the REPL to reset it).

**Comment by nbeloglazov** [comment]
I see. Though I'd like to minimize amount of code unrelated to drawing as much as possible. I've played with it a little bit and seems like following does the trick:

```clojure
(defonce sketch
  (q/defsketch sk
    :host "testproject"
    ...
    :middleware [m/fun-mode]))
```

Yes, defonce hack is needed for figwheel reloading, but I don't think that `run_sketch` function is needed. Also `index.html` can be left as it is without any modifications.

**Comment by heyarne** [comment]
I understand why you'd like to keep the sketch as simple as possible, I feel that the added benefit of being able to reset the sketch by uncommenting one line might be worth it. To clarify, my current template looks like this:

```
; this function is called in index.html
(defn ^:export run-sketch []
  (q/defsketch current-template
    :host "current-template"
    :size [500 500]
    ; setup function called only once, during sketch initialization.
    :setup setup
    ; update-state is called on each iteration before draw-state.
    :update update-state
    :draw draw-state
    ; This sketch uses functional-mode middleware.
    ; Check quil wiki for more info about middlewares and particularly
    ; fun-mode.
    :middleware [m/fun-mode]))

; uncomment this line to reset the sketch:
; (run-sketch)
```

I feel like this is clear enough in what it does, also to a beginner who might not be familiar with the whole environment. Also you don't have two symbols refering to the same thing (`sketch` and `sk`). If that doesn't convince you I can of course change it to something more similar to what you proposed, happy enough to see the pull request merged. :)

**Comment by nbeloglazov** [comment]
Yes, I didn't like having both sketch and sk in my example as it's ugly. Hm, so in your suggestion run-sketch is called from index.html the first time and then you can uncomment string to reload it without refreshing the page? Sounds reasonable and looks cleaner then mine approach. Can you update your PR with your proposed changes? Thanks a lot for doing that!

**Comment by nbeloglazov** [comment]
Thank you for the pull request!

**Comment by nbeloglazov** [comment]
Released new version of the template: https://clojars.org/quil-cljs/lein-template

**Comment by heyarne** [comment]
Nice! Thanks for your work on the library, really. Glad to see this merged!

**Pull request merged**
